name: ci
on:
  push:
    tags-ignore:
      - 'v*.*.*'
    branches:
      - '*'
  pull_request:

env:
  OCAML_COMPILER: 5.x.x

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ env.OCAML_COMPILER }}
          dune-cache: true

      - run: make install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: make lint
      - run: make format
      - run: make test
