name: release
on:
  push:
    tags:
      - "v*"

env:
  OCAML_COMPILER: 5.x.x

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ env.OCAML_COMPILER }}
          dune-cache: true

      - run: make install DUNE_PROFILE=--profile=release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: make dist

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true
